name: Update Data

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

jobs:
  update_data:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run script to update data and download images
        run: python api/updateArk.py

      - name: Archive image folder
        uses: actions/upload-artifact@v2
        with:
          name: images
          path: data/image/char

      - name: Upload JSON files to Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: JSON files
          path: conf/simple_star_list.json, conf/char_data_list.json
