name: Update Data

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

jobs:
  update_data:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run script to update data and download images
        run: |
          python updateArk.py
          mkdir -p ${{ github.workspace }}/artifacts/images
          mv data/image/char ${{ github.workspace }}/artifacts/images
          mv data/simple_star_list.json ${{ github.workspace }}/artifacts/simple_star_list.json
          mv data/char_data_list.json ${{ github.workspace }}/artifacts/char_data_list.json

      - name: Archive image folder
        uses: actions/upload-artifact@v2
        with:
          name: images
          path: artifacts/images

      - name: Upload JSON files to Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: JSON files
          path: artifacts/simple_star_list.json, artifacts/char_data_list.json
